# Generated by Django 3.1.3 on 2020-12-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des', models.CharField(default='', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='pics')),
                ('slug', models.SlugField()),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='look.store_name')),
            ],
        ),
    ]
