# Generated by Django 3.1.3 on 2020-12-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
