# Generated by Django 3.1.3 on 2020-12-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0002_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(default='', max_length=200),
        ),
    ]
