# Generated by Django 3.1.3 on 2020-12-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0010_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
