# Generated by Django 3.1.3 on 2020-12-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0011_auto_20201223_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_json',
            field=models.JSONField(max_length=5000),
        ),
    ]
