# Generated by Django 3.1.3 on 2020-12-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('look', '0012_auto_20201223_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items_json',
            field=models.CharField(max_length=100000),
        ),
    ]
